### ISSUE TITLE
Create buffer and aborts upon access of data created

### ISSUE THREAD

**Issue by gbowman2013** [havatv/qgismultidistancebufferplugin#15] opened 2017-03-28 18:11 UTC
Using qgis v2.18.4 w/ bufferplugin v1.2.2, I create a buffer around a single poly. If I try to open attribute table, zoom too, or other action that access data, I get processing error (minidump)... at end of .dmp (can't attach because it is 31Mb+) is text that may help focus:

"numpy.core.multiarray   numpy.core.multiarray failed to import  _ARRAY_API      _ARRAY_API not found    _ARRAY_API is not PyCObject object      _ARRAY_API is NULL pointer      module compiled against ABI version 0x%x but this version of numpy is 0x%x      module compiled against API version 0x%x but this version of numpy is 0x%x      FATAL: module compiled as unknown endian        FATAL: module compiled as little endian, but detected different endianness at runtime   OO      invalid work array for fft size OO      invalid work array for fft size l   OO  invalid work array for fft size OO      invalid work array for fft size l   cfftf "
![image](https://cloud.githubusercontent.com/assets/4983439/24420276/ec7049dc-13b7-11e7-8a6c-7c841a433086.png)

**Comment by havatv** [comment] 2017-03-28 23:34
Thanks for reporting!
In QGIS 2.18.4 (on Ubuntu 14.04), I created a scratch layer with a single polygon and created a multipolygon with two levels (100 and 200) using version 1.2.2 of the plugin.  No problems opening the attribute table or zoom to layer.
Does this happen for just that polygon, or for any polygon?
Is it only for single polygon layers that you experience this problem?
If you can share your data set, I could test some more.

**Comment by havatv** [comment] 2017-06-08 17:48
This issue may have been a Windows specific issue caused by QgsGeometryAnalyzer.  I assume that this issue also is fixed by #19, so I close it.  @gbowman2013, please reopen if that is not the case.

**Closed as completed by havatv** 2017-06-08 17:48 UTC
